name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS Amplify (Production)
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-app.com

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Trigger Amplify production deployment
        run: |
          echo "🚀 Production deployment triggered by push to main branch"
          echo "📊 Monitor deployment at: https://console.aws.amazon.com/amplify/"
          echo "✅ This deployment has passed all staging tests and human approval"

      - name: Create deployment tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          TAG="release-$(date +%Y%m%d-%H%M%S)"
          git tag -a "$TAG" -m "Production deployment $TAG"
          git push origin "$TAG"

      - name: Production deployment notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: '🚀 Production deployment ${{ job.status }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Rollback on failure
        if: failure()
        run: |
          echo "❌ Production deployment failed"
          echo "🔄 Manual rollback may be required"
          echo "📋 Check AWS Amplify console for details"
