name: Staging to Main Promotion

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  verify-source-branch:
    name: Verify PR is from Staging
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "❌ ERROR: Pull requests to main must come from staging branch only"
            echo "Current source branch: ${{ github.head_ref }}"
            echo ""
            echo "Workflow:"
            echo "1. Make changes in feature branches"
            echo "2. Merge/push to staging branch"
            echo "3. CI runs full test suite on staging"
            echo "4. AWS Amplify deploys to staging environment"
            echo "5. After human testing/approval, create PR from staging → main"
            exit 1
          fi
          echo "✅ Source branch verified: staging"

  final-validation:
    name: Final Validation Before Main
    runs-on: ubuntu-latest
    needs: verify-source-branch
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm run install:all

      - name: Lint
        run: |
          cd frontend && npm run lint
          cd ../backend && npm run lint

      - name: Type check
        run: |
          cd frontend && npm run type-check
          cd ../backend && npm run type-check

      - name: Run all tests
        run: npm run test:all

      - name: Build
        run: |
          cd frontend && npm run build
          cd ../backend && npm run build

  security-check:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: verify-source-branch
    steps:
      - uses: actions/checkout@v4

      - name: Run npm audit
        run: |
          cd frontend && npm audit --audit-level=high
          cd ../backend && npm audit --audit-level=high

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  approval-required:
    name: Approval Required
    runs-on: ubuntu-latest
    needs: [final-validation, security-check]
    steps:
      - name: Require approval
        run: |
          echo "✅ All automated checks passed"
          echo ""
          echo "⚠️  HUMAN APPROVAL REQUIRED"
          echo ""
          echo "Before merging to main:"
          echo "1. Verify staging environment is stable"
          echo "2. Confirm all manual testing is complete"
          echo "3. Review all changes in this PR"
          echo "4. Get approval from team lead/reviewer"
          echo ""
          echo "After approval, merge this PR to deploy to production"
